language: ruby

branchs:
  only:
    - master

addons:
  ssh_known_hosts:
    - ${SERVER_HOST}

before_install:
  - openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv
    -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host ${SERVER_HOST}\n\tStrictHostKeyChecking no\n\tIdentityFile ~/.ssh/id_rsa" >> ~/.ssh/config

after_success:
- ssh ${SERVER_USER}@${SERVER_HOST} -o StrictHostKeyChecking=no 'cd ~/.www/zoharyips.github.io && git pull'