language: ruby

branchs:
  only:
    - master

addons:
  ssh_known_hosts:
    - ${SERVER_HOST}

before_install:
  - openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv
    -in id_rsa.enc -out id_rsa -d
  - chmod 600 id_rsa
  - ssh-add id_rsa

script:
  - bundle install
  - bundle exec jekyll build

after_success:
- scp -o stricthostkeychecking=no -r ./_site ${SERVER_USER}@${SERVER_HOST}:~/zoharyip.club